$(document).ready ->
  foregroundColor = 'ffffff'
  backgroundColor = '000000'

  buildUrl = (width, height, foreground, background, name) ->
    '/api/name/' + width + '/' + height + '/' + background + '/' + foreground + '/' + name

  buildMoleculeOnlyUrl = (width, height, foreground, name) ->
    '/api/name/' + width + '/' + height + '/' + foreground + '/' + name

  refreshPreview = ->
    $('body').css('background', 'url(' + buildMoleculeOnlyUrl(1920, 1280, foregroundColor, $('.comp-name').val()) + ')').css('background-color', '#' + backgroundColor).css('background-position', '50% 50%').css 'background-repeat', 'no-repeat'
    return

  $('.picker-fg').on 'change', (e) ->
    foregroundColor = $(e.target).val().substring(1)
    refreshPreview()
    return
  $('.picker-bg').on 'change', (e) ->
    backgroundColor = $(e.target).val().substring(1)
    refreshPreview()
    return
  $('.update-btn').on 'click', (e) ->
    refreshPreview()
    return
  $('.download-btn').on 'click', (e) ->
    window.open buildUrl(1920, 1280, foregroundColor, backgroundColor, $('.comp-name').val()), 'Image', 'width=largeImage.stylewidth,height=largeImage.style.height,resizable=1'
    return
  $('.picker-fg').spectrum
    color: '#' + foregroundColor
    showAlpha: false
    clickoutFiresChange: true
    chooseText: 'Update'
    preferredFormat: 'hex'
  $('.picker-bg').spectrum
    color: '#' + backgroundColor
    showAlpha: false
    clickoutFiresChange: true
    chooseText: 'Update'
    preferredFormat: 'hex'
  refreshPreview()
  return

# ---
# generated by js2coffee 2.2.0